import csv
import argparse
import random
import unicodedata
from pathlib import Path


def strip_diacritics(s: str) -> str:
    nfkd = unicodedata.normalize('NFD', s)
    stripped = ''.join(ch for ch in nfkd if unicodedata.category(ch) != 'Mn')
    return unicodedata.normalize('NFC', stripped)


def split_csv_train_dev(csv_path, target_col='labels', source_col=None, out_dir='data', dev_frac=0.05, seed=42, max_lines=None, delimiter=','):
    csv_path = Path(csv_path)
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    pairs = []
    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f, delimiter=delimiter)
        if target_col not in reader.fieldnames:
            raise ValueError(f"CSV must contain target column '{target_col}'. Found: {reader.fieldnames}")
        if source_col is not None and source_col not in reader.fieldnames:
            raise ValueError(f"CSV does not contain source column '{source_col}'. Found: {reader.fieldnames}")
        for i, row in enumerate(reader):
            tgt = row[target_col].strip()
            if not tgt:
                continue
            if source_col is not None:
                src = row[source_col].strip()
            else:
                src = strip_diacritics(tgt)
            if not src:
                continue
            pairs.append((src, tgt))
            if max_lines and len(pairs) >= max_lines:
                break
    random.Random(seed).shuffle(pairs)
    n = len(pairs)
    n_dev = int(n * dev_frac)
    dev_pairs = pairs[:n_dev]
    train_pairs = pairs[n_dev:]
    def write_pairs(pairs, prefix):
        src_out = out_dir / f"{prefix}_undiacritic.txt"
        tgt_out = out_dir / f"{prefix}_diacritic.txt"
        with open(src_out, 'w', encoding='utf-8') as fs, open(tgt_out, 'w', encoding='utf-8') as ft:
            for s,t in pairs:
                fs.write(s + '\n')
                ft.write(t + '\n')
    write_pairs(train_pairs, 'train')
    write_pairs(dev_pairs, 'dev')
    print(f'Wrote {len(train_pairs)} train and {len(dev_pairs)} dev examples to {out_dir}')

if __name__ == '__main__':
    p = argparse.ArgumentParser()
    p.add_argument('csv_path')
    p.add_argument('--target-col', '-t', default='labels')
    p.add_argument('--source-col', '-s', default=None, help='Optional source column; if omitted, source will be generated by stripping diacritics from target')
    p.add_argument('--out-dir', '-o', default='data')
    p.add_argument('--dev-frac', type=float, default=0.05)
    p.add_argument('--seed', type=int, default=42)
    p.add_argument('--max-lines', type=int, default=None)
    p.add_argument('--delimiter', default=',')
    args = p.parse_args()
    split_csv_train_dev(args.csv_path, target_col=args.target_col, source_col=args.source_col, out_dir=args.out_dir, dev_frac=args.dev_frac, seed=args.seed, max_lines=args.max_lines, delimiter=args.delimiter)
